[workspace]
resolver = "3"
members = ["examples/*"]

[package]
name = "stm32wb-hci"
edition = "2024"
version = "0.17.4"
authors = [
    "Daniel Gallagher <pdanielgallagher@gmail.com>",
    "Ghaith Oueslati <ghaith.oueslati@enis.tn>",
]
categories = ["embedded", "hardware-support", "no-std", "asynchronous"]
description = "Implementation of the Bluetooth HCI for the STM32WB family"
keywords = ["ble", "bluetooth", "stm32"]
license = "MIT/Apache-2.0"
repository = "https://github.com/OueslatiGhaith/stm32wb-hci"
readme = "README.md"
exclude = ["tests"]

[dependencies]
bitflags = "2"
bt-hci = { version = "0.8.1", git = "https://github.com/embassy-rs/bt-hci/", rev = "6613764" }
byteorder = { version = "1", default-features = false }
defmt = { version = "1", optional = true }
embedded-io = "0.7.1"
embedded-io-async = "0.7.0"

[target.'cfg(windows)'.dependencies]
critical-section = { version = "1.2", features = ["std"]}

[target.'cfg(unix)'.dependencies]
critical-section = { version = "1.2", features = ["std"]}

[dev-dependencies]
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros"] }

[features]
defmt = ["dep:defmt", "bt-hci/defmt"]

[profile.dev]
debug = 2

[profile.release]
debug = 2
