use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;
use std::path::PathBuf;

use crate::FirmwareVersion;
use crate::wire::WireReport;

/// The source-level catalog from which an entry was discovered.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum CoverageOrigin {
    VendorAutoSource,
    VendorCommandCatalog,
    VendorEventCatalog,
    /// Generated `ble_hci_le.c` / `ble_events.c` standard-HCI catalog entry.
    StandardHciAutoSource,
    /// Public surface supplied by the re-exported `bt-hci` dependency.
    StandardHciProvider,
    /// Public STM32WB-specific standard-HCI command type in this crate.
    StandardHciExtension,
}

impl CoverageOrigin {
    pub fn as_str(self) -> &'static str {
        match self {
            Self::VendorAutoSource => "vendor-auto-source",
            Self::VendorCommandCatalog => "vendor-command-catalog",
            Self::VendorEventCatalog => "vendor-event-catalog",
            Self::StandardHciAutoSource => "standard-hci-auto-source",
            Self::StandardHciProvider => "standard-hci-provider",
            Self::StandardHciExtension => "standard-hci-extension",
        }
    }
}

/// One command or event implementation discovered by a source extractor.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct CoverageEntry {
    pub code: u16,
    pub name: String,
    pub origin: CoverageOrigin,
    pub location: Option<PathBuf>,
}

impl CoverageEntry {
    pub fn new(code: u16, name: impl Into<String>, origin: CoverageOrigin) -> Self {
        Self {
            code,
            name: name.into(),
            origin,
            location: None,
        }
    }

    pub fn at(mut self, location: PathBuf) -> Self {
        self.location = Some(location);
        self
    }
}

/// Commands and events discovered from a protocol catalog.
#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct ProtocolCoverage {
    pub commands: Vec<CoverageEntry>,
    pub events: Vec<CoverageEntry>,
}

impl ProtocolCoverage {
    pub fn command_codes(&self) -> BTreeSet<u16> {
        self.commands.iter().map(|entry| entry.code).collect()
    }

    pub fn event_codes(&self) -> BTreeSet<u16> {
        self.events.iter().map(|entry| entry.code).collect()
    }

    pub fn names_by_command_code(&self) -> BTreeMap<u16, Vec<String>> {
        names_by_code(&self.commands)
    }

    pub fn names_by_event_code(&self) -> BTreeMap<u16, Vec<String>> {
        names_by_code(&self.events)
    }
}

/// Standard HCI uses three distinct numerical namespaces: full command
/// opcodes, ordinary event codes, and LE Meta Event subevent codes. Keeping
/// them separate prevents an event code from accidentally satisfying a command
/// coverage claim.
#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct StandardHciCoverage {
    pub commands: Vec<CoverageEntry>,
    pub events: Vec<CoverageEntry>,
    pub le_meta_events: Vec<CoverageEntry>,
}

fn names_by_code(entries: &[CoverageEntry]) -> BTreeMap<u16, Vec<String>> {
    let mut names = BTreeMap::<u16, Vec<String>>::new();
    for entry in entries {
        let values = names.entry(entry.code).or_default();
        if !values.contains(&entry.name) {
            values.push(entry.name.clone());
        }
    }
    for values in names.values_mut() {
        values.sort();
    }
    names
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct CoverageDifference {
    pub code: u16,
    pub expected: Vec<String>,
    pub observed: Vec<String>,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ExcludedCode {
    pub code: u16,
    pub reason: String,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct CheckReport {
    firmware: FirmwareVersion,
    cube_tag: String,
    /// The complete vendor catalog read at the selected CubeWB tag.
    vendor: ProtocolCoverage,
    /// Coverage derived from active declarative command and event catalogs.
    active_api: ProtocolCoverage,
    /// Standard HCI command/event catalogs generated by the selected CubeWB
    /// tag.
    standard_hci: StandardHciCoverage,
    /// Standard HCI surface publicly provided by this crate (the `bt-hci`
    /// re-export plus local STM32WB extensions).
    standard_hci_provider: StandardHciCoverage,
    missing_commands: Vec<CoverageDifference>,
    extraneous_commands: Vec<CoverageDifference>,
    missing_events: Vec<CoverageDifference>,
    extraneous_events: Vec<CoverageDifference>,
    missing_standard_hci_commands: Vec<CoverageDifference>,
    missing_standard_hci_events: Vec<CoverageDifference>,
    missing_standard_hci_le_meta_events: Vec<CoverageDifference>,
    /// Envelope-level vendor command and event wire checks. Both definite
    /// differences and unavailable evidence make the report non-compliant.
    wire: WireReport,
    excluded_commands: Vec<ExcludedCode>,
    excluded_events: Vec<ExcludedCode>,
}

impl CheckReport {
    /// Build a report from source inventories and derive every comparison.
    #[allow(clippy::too_many_arguments)]
    pub fn new(
        firmware: FirmwareVersion,
        vendor: ProtocolCoverage,
        active_api: ProtocolCoverage,
        standard_hci: StandardHciCoverage,
        standard_hci_provider: StandardHciCoverage,
        wire: WireReport,
        excluded_commands: BTreeMap<u16, String>,
        excluded_events: BTreeMap<u16, String>,
    ) -> Self {
        let missing_commands = differences(
            &vendor.names_by_command_code(),
            &active_api.names_by_command_code(),
            &excluded_commands,
            true,
        );
        let extraneous_commands = differences(
            &vendor.names_by_command_code(),
            &active_api.names_by_command_code(),
            &excluded_commands,
            false,
        );
        let missing_events = differences(
            &vendor.names_by_event_code(),
            &active_api.names_by_event_code(),
            &excluded_events,
            true,
        );
        let extraneous_events = differences(
            &vendor.names_by_event_code(),
            &active_api.names_by_event_code(),
            &excluded_events,
            false,
        );
        let missing_standard_hci_commands =
            missing_differences(&standard_hci.commands, &standard_hci_provider.commands);
        let missing_standard_hci_events =
            missing_differences(&standard_hci.events, &standard_hci_provider.events);
        let missing_standard_hci_le_meta_events = missing_differences(
            &standard_hci.le_meta_events,
            &standard_hci_provider.le_meta_events,
        );

        Self {
            firmware,
            cube_tag: firmware.cube_tag(),
            vendor,
            active_api,
            standard_hci,
            standard_hci_provider,
            missing_commands,
            extraneous_commands,
            missing_events,
            extraneous_events,
            missing_standard_hci_commands,
            missing_standard_hci_events,
            missing_standard_hci_le_meta_events,
            wire,
            excluded_commands: exclusions_to_vec(excluded_commands),
            excluded_events: exclusions_to_vec(excluded_events),
        }
    }

    pub const fn firmware(&self) -> FirmwareVersion {
        self.firmware
    }

    pub fn cube_tag(&self) -> &str {
        &self.cube_tag
    }

    pub const fn vendor(&self) -> &ProtocolCoverage {
        &self.vendor
    }

    pub const fn active_api(&self) -> &ProtocolCoverage {
        &self.active_api
    }

    pub const fn standard_hci(&self) -> &StandardHciCoverage {
        &self.standard_hci
    }

    pub const fn standard_hci_provider(&self) -> &StandardHciCoverage {
        &self.standard_hci_provider
    }

    pub fn missing_commands(&self) -> &[CoverageDifference] {
        &self.missing_commands
    }

    pub fn extraneous_commands(&self) -> &[CoverageDifference] {
        &self.extraneous_commands
    }

    pub fn missing_events(&self) -> &[CoverageDifference] {
        &self.missing_events
    }

    pub fn extraneous_events(&self) -> &[CoverageDifference] {
        &self.extraneous_events
    }

    pub fn missing_standard_hci_commands(&self) -> &[CoverageDifference] {
        &self.missing_standard_hci_commands
    }

    pub fn missing_standard_hci_events(&self) -> &[CoverageDifference] {
        &self.missing_standard_hci_events
    }

    pub fn missing_standard_hci_le_meta_events(&self) -> &[CoverageDifference] {
        &self.missing_standard_hci_le_meta_events
    }

    pub const fn wire(&self) -> &WireReport {
        &self.wire
    }

    pub fn excluded_commands(&self) -> &[ExcludedCode] {
        &self.excluded_commands
    }

    pub fn excluded_events(&self) -> &[ExcludedCode] {
        &self.excluded_events
    }

    pub fn is_compliant(&self) -> bool {
        self.missing_commands.is_empty()
            && self.extraneous_commands.is_empty()
            && self.missing_events.is_empty()
            && self.extraneous_events.is_empty()
            && self.missing_standard_hci_commands.is_empty()
            && self.missing_standard_hci_events.is_empty()
            && self.missing_standard_hci_le_meta_events.is_empty()
            && self.wire.differences.is_empty()
            && self.wire.unavailable.is_empty()
    }

    pub fn to_human(&self) -> String {
        let mut output = String::new();
        let _ = writeln!(
            output,
            "STM32WB firmware compliance: {} ({})",
            self.firmware, self.cube_tag
        );
        let _ = writeln!(
            output,
            "scope: active declarative vendor catalogs + public standard-HCI provider"
        );
        let _ = writeln!(
            output,
            "catalogs: vendor {} command IDs / {} event IDs; active crate {} command IDs / {} event IDs",
            self.vendor.command_codes().len(),
            self.vendor.event_codes().len(),
            self.active_api.command_codes().len(),
            self.active_api.event_codes().len(),
        );
        let _ = writeln!(
            output,
            "standard HCI: CubeWB {} command opcodes / {} events / {} LE subevents; provider {} / {} / {}",
            self.standard_hci.commands.len(),
            self.standard_hci.events.len(),
            self.standard_hci.le_meta_events.len(),
            self.standard_hci_provider.commands.len(),
            self.standard_hci_provider.events.len(),
            self.standard_hci_provider.le_meta_events.len(),
        );
        write_differences(&mut output, "missing commands", &self.missing_commands);
        write_differences(
            &mut output,
            "extraneous commands",
            &self.extraneous_commands,
        );
        write_differences(&mut output, "missing events", &self.missing_events);
        write_differences(&mut output, "extraneous events", &self.extraneous_events);
        write_differences(
            &mut output,
            "missing standard HCI commands",
            &self.missing_standard_hci_commands,
        );
        write_differences(
            &mut output,
            "missing standard HCI events",
            &self.missing_standard_hci_events,
        );
        write_differences(
            &mut output,
            "missing standard HCI LE Meta events",
            &self.missing_standard_hci_le_meta_events,
        );
        let _ = writeln!(
            output,
            "wire envelopes: {} checked / {} differences / {} unavailable",
            self.wire.checked,
            self.wire.differences.len(),
            self.wire.unavailable.len(),
        );
        write_wire_differences(&mut output, &self.wire);
        write_wire_unavailable(&mut output, &self.wire);
        write_exclusions(&mut output, "excluded commands", &self.excluded_commands);
        write_exclusions(&mut output, "excluded events", &self.excluded_events);
        let _ = writeln!(
            output,
            "result: {}",
            if self.is_compliant() {
                "compliant"
            } else {
                "non-compliant"
            }
        );
        output
    }
}

fn write_differences(output: &mut String, label: &str, differences: &[CoverageDifference]) {
    let _ = writeln!(output, "{label}: {}", differences.len());
    for difference in differences {
        let expected = if difference.expected.is_empty() {
            "-".to_owned()
        } else {
            difference.expected.join(", ")
        };
        let observed = if difference.observed.is_empty() {
            "-".to_owned()
        } else {
            difference.observed.join(", ")
        };
        let _ = writeln!(
            output,
            "  0x{:04X}: vendor [{expected}], crate [{observed}]",
            difference.code
        );
    }
}

fn write_exclusions(output: &mut String, label: &str, exclusions: &[ExcludedCode]) {
    if exclusions.is_empty() {
        return;
    }
    let _ = writeln!(output, "{label}: {}", exclusions.len());
    for exclusion in exclusions {
        let _ = writeln!(output, "  0x{:04X}: {}", exclusion.code, exclusion.reason);
    }
}

fn write_wire_differences(output: &mut String, wire: &WireReport) {
    for difference in &wire.differences {
        let _ = writeln!(
            output,
            "  wire 0x{:04X} ({}): {}",
            difference.code, difference.command, difference.issue
        );
    }
}

fn write_wire_unavailable(output: &mut String, wire: &WireReport) {
    for unavailable in &wire.unavailable {
        let _ = writeln!(
            output,
            "  wire unavailable 0x{:04X} ({}): {}",
            unavailable.code, unavailable.command, unavailable.reason
        );
    }
}

fn missing_differences(
    expected: &[CoverageEntry],
    provider: &[CoverageEntry],
) -> Vec<CoverageDifference> {
    let expected = names_by_code(expected);
    let provider = names_by_code(provider);
    expected
        .iter()
        .filter(|(code, _)| !provider.contains_key(code))
        .map(|(code, names)| CoverageDifference {
            code: *code,
            expected: names.clone(),
            observed: Vec::new(),
        })
        .collect()
}

fn differences(
    expected: &BTreeMap<u16, Vec<String>>,
    observed: &BTreeMap<u16, Vec<String>>,
    exclusions: &BTreeMap<u16, String>,
    missing: bool,
) -> Vec<CoverageDifference> {
    let keys: Box<dyn Iterator<Item = &u16>> = if missing {
        Box::new(expected.keys())
    } else {
        Box::new(observed.keys())
    };

    keys.filter_map(|code| {
        if exclusions.contains_key(code) {
            return None;
        }
        let in_expected = expected.contains_key(code);
        let in_observed = observed.contains_key(code);
        if (missing && !in_observed) || (!missing && !in_expected) {
            Some(CoverageDifference {
                code: *code,
                expected: expected.get(code).cloned().unwrap_or_default(),
                observed: observed.get(code).cloned().unwrap_or_default(),
            })
        } else {
            None
        }
    })
    .collect()
}

fn exclusions_to_vec(exclusions: BTreeMap<u16, String>) -> Vec<ExcludedCode> {
    exclusions
        .into_iter()
        .map(|(code, reason)| ExcludedCode { code, reason })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn comparison_is_by_wire_code_not_spelling() {
        let vendor = ProtocolCoverage {
            commands: vec![CoverageEntry::new(
                0x81,
                "aci_gap_set_non_discoverable",
                CoverageOrigin::VendorAutoSource,
            )],
            events: vec![],
        };
        let active = ProtocolCoverage {
            commands: vec![CoverageEntry::new(
                0x81,
                "set_non_discoverable",
                CoverageOrigin::VendorCommandCatalog,
            )],
            events: vec![],
        };
        let report = CheckReport::new(
            FirmwareVersion::new(0, 15, 0),
            vendor.clone(),
            active,
            StandardHciCoverage::default(),
            StandardHciCoverage::default(),
            WireReport::default(),
            BTreeMap::new(),
            BTreeMap::new(),
        );
        assert!(report.is_compliant());
        assert!(report.to_json().contains("\"compliant\":true"));
    }

    #[test]
    fn standard_and_wire_differences_make_a_report_noncompliant() {
        let report = CheckReport::new(
            FirmwareVersion::new(0, 17, 1),
            ProtocolCoverage::default(),
            ProtocolCoverage::default(),
            StandardHciCoverage {
                commands: vec![CoverageEntry::new(
                    0x2041,
                    "hci_le_set_extended_scan_parameters",
                    CoverageOrigin::StandardHciAutoSource,
                )],
                ..StandardHciCoverage::default()
            },
            StandardHciCoverage::default(),
            WireReport {
                checked: 1,
                differences: vec![crate::wire::WireDifference {
                    code: 0x92,
                    command: "GapConfigureWhitelist".into(),
                    issue: "fixture mismatch".into(),
                }],
                unavailable: Vec::new(),
            },
            BTreeMap::new(),
            BTreeMap::new(),
        );
        assert!(!report.is_compliant());
        assert_eq!(report.missing_standard_hci_commands().len(), 1);
        assert!(report.to_json().contains("\"wire\""));
    }

    #[test]
    fn unavailable_wire_evidence_makes_a_report_noncompliant() {
        let report = CheckReport::new(
            FirmwareVersion::new(0, 17, 1),
            ProtocolCoverage::default(),
            ProtocolCoverage::default(),
            StandardHciCoverage::default(),
            StandardHciCoverage::default(),
            WireReport::default(),
            BTreeMap::new(),
            BTreeMap::new(),
        );
        assert!(report.is_compliant());

        let report = CheckReport::new(
            FirmwareVersion::new(0, 17, 1),
            ProtocolCoverage::default(),
            ProtocolCoverage::default(),
            StandardHciCoverage::default(),
            StandardHciCoverage::default(),
            WireReport {
                checked: 0,
                differences: Vec::new(),
                unavailable: vec![crate::wire::WireUnavailable {
                    code: 0x9200,
                    command: "CoprocessorReady".into(),
                    reason: "missing external payload evidence".into(),
                }],
            },
            BTreeMap::new(),
            BTreeMap::new(),
        );

        assert!(!report.is_compliant());
        assert!(report.to_human().contains("result: non-compliant"));
        assert!(report.to_json().contains("\"compliant\":false"));
    }

    #[test]
    fn json_serialization_preserves_the_report_shape() {
        let vendor = ProtocolCoverage {
            commands: vec![CoverageEntry::new(
                0x0010,
                "aci_expected_command",
                CoverageOrigin::VendorAutoSource,
            )],
            events: vec![CoverageEntry::new(
                0x0020,
                "aci_expected_event",
                CoverageOrigin::VendorAutoSource,
            )],
        };
        let active_api = ProtocolCoverage {
            commands: vec![CoverageEntry::new(
                0x0011,
                "crate_extra_command",
                CoverageOrigin::VendorCommandCatalog,
            )],
            events: Vec::new(),
        };
        let report = CheckReport::new(
            FirmwareVersion::new(0, 15, 0),
            vendor,
            active_api,
            StandardHciCoverage::default(),
            StandardHciCoverage::default(),
            WireReport {
                checked: 2,
                differences: vec![crate::wire::WireDifference {
                    code: 0x0040,
                    command: "WireCommand".into(),
                    issue: "mismatched return buffer".into(),
                }],
                unavailable: vec![crate::wire::WireUnavailable {
                    code: 0x0041,
                    command: "CapacityCommand".into(),
                    reason: "capacity is firmware dependent".into(),
                }],
            },
            BTreeMap::from([(0x00EE, "reason with a quote (\") and newline\n".into())]),
            BTreeMap::new(),
        );

        let json: serde_json::Value = serde_json::from_str(&report.to_json()).unwrap();

        assert_eq!(
            json,
            serde_json::json!({
                "firmware": "0.15.0",
                "cube_tag": "v1.15.0",
                "compliant": false,
                "catalog_counts": {
                    "vendor_command_ids": 1,
                    "vendor_event_ids": 1,
                    "active_command_ids": 1,
                    "active_event_ids": 0,
                    "standard_hci_command_opcodes": 0,
                    "standard_hci_event_codes": 0,
                    "standard_hci_le_meta_event_codes": 0,
                    "standard_hci_provider_command_opcodes": 0,
                    "standard_hci_provider_event_codes": 0,
                    "standard_hci_provider_le_meta_event_codes": 0,
                },
                "missing_commands": [{
                    "code": 0x0010,
                    "hex": "0x0010",
                    "expected": ["aci_expected_command"],
                    "observed": [],
                }],
                "extraneous_commands": [{
                    "code": 0x0011,
                    "hex": "0x0011",
                    "expected": [],
                    "observed": ["crate_extra_command"],
                }],
                "missing_events": [{
                    "code": 0x0020,
                    "hex": "0x0020",
                    "expected": ["aci_expected_event"],
                    "observed": [],
                }],
                "extraneous_events": [],
                "missing_standard_hci_commands": [],
                "missing_standard_hci_events": [],
                "missing_standard_hci_le_meta_events": [],
                "wire": {
                    "checked": 2,
                    "differences": [{
                        "code": 0x0040,
                        "hex": "0x0040",
                        "command": "WireCommand",
                        "issue": "mismatched return buffer",
                    }],
                    "unavailable": [{
                        "code": 0x0041,
                        "hex": "0x0041",
                        "command": "CapacityCommand",
                        "reason": "capacity is firmware dependent",
                    }],
                },
                "excluded_commands": [{
                    "code": 0x00EE,
                    "hex": "0x00EE",
                    "reason": "reason with a quote (\") and newline\n",
                }],
                "excluded_events": [],
            })
        );
    }
}
