//! Internal declarations for semantic values with canonical HCI wire forms.

mod decode;

pub use decode::{
    BoundedBytes, BoundedItems, EventBytes, EventItems, EventItemsIter, HciDecodeCountedBytes,
    HciDecodeCountedItems, HciDecodeTrailingBytes,
};
pub(crate) use decode::{
    DecodeError, decode_counted_bytes, decode_counted_items, decode_fixed_field,
    decode_prefixed_bytes, decode_trailing_bytes,
};

/// A value with an exact, canonical representation in an HCI request.
///
/// `N` is part of the trait so a declarative field whose schema says
/// `field: Type => N` only compiles when `Type` explicitly supports that wire
/// width. Implementations must not rely on Rust structure layout or native
/// endianness.
pub trait HciEncodeField<const N: usize> {
    /// Write exactly `N` bytes to a synchronous HCI writer.
    fn write_hci_field<W: embedded_io::Write>(&self, writer: W) -> Result<(), W::Error>;

    /// Write exactly `N` bytes to an asynchronous HCI writer.
    async fn write_hci_field_async<W: embedded_io_async::Write>(
        &self,
        writer: W,
    ) -> Result<(), W::Error>;
}

/// A value decoded from an exact-width HCI field.
///
/// Implementations receive exactly `N` bytes and must apply the protocol's
/// validity rules rather than interpreting arbitrary Rust memory.
pub trait HciDecodeField<const N: usize>: Sized {
    /// Decode one exact-width field.
    fn from_hci_field(bytes: &[u8; N]) -> Result<Self, bt_hci::FromHciBytesError>;
}

/// A semantic value decoded from an exact-width vendor-event field.
///
/// Event decoding retains the vendor event's structured diagnostics while
/// sharing its fixed-width declaration with command adapters generated by
/// [`stm32wb_hci_macros::wire_type!`].
///
/// An unsupported type/width pair is a compile-time error:
///
/// ```compile_fail
/// use stm32wb_hci::vendor::event::HciEventField;
///
/// fn requires_two_bytes<T: HciEventField<2>>() {}
/// requires_two_bytes::<bool>();
/// ```
pub trait HciEventField<const N: usize>: Sized {
    /// Decode one exact-width vendor-event field.
    fn from_hci_event_field(bytes: &[u8; N]) -> Result<Self, crate::vendor::event::Error>;
}

/// An event item that can be reconstructed infallibly after its bytes have
/// already passed [`HciEventField`] validation.
///
/// This is an implementation detail of borrowed counted-item event views.
#[doc(hidden)]
pub trait HciEventItem<const N: usize>: HciEventField<N> {
    fn from_validated_hci_event_field(bytes: &[u8; N]) -> Self;
}

/// An integer type that can prefix a counted declarative field.
#[doc(hidden)]
pub trait HciCount<const N: usize>: HciEncodeField<N> + Copy {
    const MAX: usize;

    fn from_usize(value: usize) -> Option<Self>;

    fn to_usize(self) -> usize;
}

impl HciCount<1> for u8 {
    const MAX: usize = u8::MAX as usize;

    fn from_usize(value: usize) -> Option<Self> {
        value.try_into().ok()
    }

    fn to_usize(self) -> usize {
        usize::from(self)
    }
}

impl HciCount<2> for u16 {
    const MAX: usize = u16::MAX as usize;

    fn from_usize(value: usize) -> Option<Self> {
        value.try_into().ok()
    }

    fn to_usize(self) -> usize {
        usize::from(self)
    }
}

stm32wb_hci_macros::wire_type! {
    adapters: [command, event];
    primitive u8 => 1;
}

stm32wb_hci_macros::wire_type! {
    adapters: [command];
    primitive i8 => 1;
}

stm32wb_hci_macros::wire_type! {
    adapters: [command, event];
    primitive u16 => 2;
}

stm32wb_hci_macros::wire_type! {
    adapters: [command];
    primitive i16 => 2;
}

stm32wb_hci_macros::wire_type! {
    adapters: [command, event];
    primitive u32 => 4;
}

stm32wb_hci_macros::wire_type! {
    adapters: [command];
    primitive i32 => 4;
}

stm32wb_hci_macros::wire_type! {
    adapters: [command];
    primitive u64 => 8;
}

stm32wb_hci_macros::wire_type! {
    adapters: [command];
    primitive i64 => 8;
}

impl HciEncodeField<1> for bool {
    fn write_hci_field<W: embedded_io::Write>(&self, mut writer: W) -> Result<(), W::Error> {
        writer.write_all(&[u8::from(*self)])
    }

    async fn write_hci_field_async<W: embedded_io_async::Write>(
        &self,
        mut writer: W,
    ) -> Result<(), W::Error> {
        writer.write_all(&[u8::from(*self)]).await
    }
}

impl HciDecodeField<1> for bool {
    fn from_hci_field(bytes: &[u8; 1]) -> Result<Self, bt_hci::FromHciBytesError> {
        match bytes[0] {
            0 => Ok(false),
            1 => Ok(true),
            _ => Err(bt_hci::FromHciBytesError::InvalidValue),
        }
    }
}

impl HciEventField<1> for bool {
    fn from_hci_event_field(bytes: &[u8; 1]) -> Result<Self, crate::vendor::event::Error> {
        match bytes[0] {
            0 => Ok(false),
            1 => Ok(true),
            value => Err(crate::vendor::event::Error::Vendor(
                crate::vendor::event::VendorError::BadBooleanValue(value),
            )),
        }
    }
}

impl<const N: usize> HciEncodeField<N> for [u8; N] {
    fn write_hci_field<W: embedded_io::Write>(&self, mut writer: W) -> Result<(), W::Error> {
        writer.write_all(self)
    }

    async fn write_hci_field_async<W: embedded_io_async::Write>(
        &self,
        mut writer: W,
    ) -> Result<(), W::Error> {
        writer.write_all(self).await
    }
}

impl<const N: usize> HciDecodeField<N> for [u8; N] {
    fn from_hci_field(bytes: &[u8; N]) -> Result<Self, bt_hci::FromHciBytesError> {
        Ok(*bytes)
    }
}

impl<const N: usize> HciEventField<N> for [u8; N] {
    fn from_hci_event_field(bytes: &[u8; N]) -> Result<Self, crate::vendor::event::Error> {
        Ok(*bytes)
    }
}

impl<T, const N: usize> HciEncodeField<N> for &T
where
    T: HciEncodeField<N>,
{
    fn write_hci_field<W: embedded_io::Write>(&self, writer: W) -> Result<(), W::Error> {
        T::write_hci_field(self, writer)
    }

    async fn write_hci_field_async<W: embedded_io_async::Write>(
        &self,
        writer: W,
    ) -> Result<(), W::Error> {
        T::write_hci_field_async(self, writer).await
    }
}

stm32wb_hci_macros::wire_type! {
    adapters: [command, event];
    transparent bt_hci::param::ConnHandle: u16 => 2;
}

stm32wb_hci_macros::wire_type! {
    adapters: [command];
    transparent bt_hci::param::BdAddr: [u8; 6] => 6;
}

stm32wb_hci_macros::wire_type! {
    adapters: [command, event];
    transparent crate::types::AttributeHandle: u16 => 2;
}
